/*
 * Copyright 1999-2018 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/******************************************/
/*   表名称 = CONFIG_INFO                  */
/******************************************/
CREATE TABLE CONFIG_INFO (
    ID BIGINT NOT NULL IDENTITY(1,1),
    DATA_ID VARCHAR(255) NOT NULL,
    GROUP_ID VARCHAR(128) DEFAULT NULL,
    CONTENT CLOB NOT NULL,
    MD5 VARCHAR(32) DEFAULT NULL,
    GMT_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    GMT_MODIFIED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SRC_USER CLOB,
    SRC_IP VARCHAR(50) DEFAULT NULL,
    APP_NAME VARCHAR(128) DEFAULT NULL,
    TENANT_ID VARCHAR(128) DEFAULT '',
    C_DESC VARCHAR(256) DEFAULT NULL,
    C_USE VARCHAR(64) DEFAULT NULL,
    EFFECT VARCHAR(64) DEFAULT NULL,
    TYPE VARCHAR(64) DEFAULT NULL,
    C_SCHEMA CLOB,
    ENCRYPTED_DATA_KEY VARCHAR(1024) NOT NULL DEFAULT ''
);

-- 主键和索引
ALTER TABLE CONFIG_INFO ADD CONSTRAINT PK_CONFIG_INFO PRIMARY KEY (ID);
CREATE UNIQUE INDEX UK_CONFIGINFO_DATAGROUPTENANT ON CONFIG_INFO (DATA_ID, GROUP_ID, TENANT_ID);

-- 表注释和列注释
COMMENT ON TABLE CONFIG_INFO IS 'config_info';
COMMENT ON COLUMN CONFIG_INFO.ID IS 'id';
COMMENT ON COLUMN CONFIG_INFO.DATA_ID IS 'data_id';
COMMENT ON COLUMN CONFIG_INFO.GROUP_ID IS 'group_id';
COMMENT ON COLUMN CONFIG_INFO.CONTENT IS 'content';
COMMENT ON COLUMN CONFIG_INFO.MD5 IS 'md5';
COMMENT ON COLUMN CONFIG_INFO.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN CONFIG_INFO.GMT_MODIFIED IS '修改时间';
COMMENT ON COLUMN CONFIG_INFO.SRC_USER IS 'source user';
COMMENT ON COLUMN CONFIG_INFO.SRC_IP IS 'source ip';
COMMENT ON COLUMN CONFIG_INFO.APP_NAME IS 'app_name';
COMMENT ON COLUMN CONFIG_INFO.TENANT_ID IS '租户字段';
COMMENT ON COLUMN CONFIG_INFO.C_DESC IS 'configuration description';
COMMENT ON COLUMN CONFIG_INFO.C_USE IS 'configuration usage';
COMMENT ON COLUMN CONFIG_INFO.EFFECT IS '配置生效的描述';
COMMENT ON COLUMN CONFIG_INFO.TYPE IS '配置的类型';
COMMENT ON COLUMN CONFIG_INFO.C_SCHEMA IS '配置的模式';
COMMENT ON COLUMN CONFIG_INFO.ENCRYPTED_DATA_KEY IS '密钥';

/******************************************/
/*   表名称 = CONFIG_INFO_GRAY             */
/******************************************/
CREATE TABLE CONFIG_INFO_GRAY (
    ID BIGINT NOT NULL IDENTITY(1,1),
    DATA_ID VARCHAR(255) NOT NULL,
    GROUP_ID VARCHAR(128) NOT NULL,
    CONTENT CLOB NOT NULL,
    MD5 VARCHAR(32) DEFAULT NULL,
    SRC_USER CLOB,
    SRC_IP VARCHAR(100) DEFAULT NULL,
    GMT_CREATE DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    GMT_MODIFIED DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    APP_NAME VARCHAR(128) DEFAULT NULL,
    TENANT_ID VARCHAR(128) DEFAULT '',
    GRAY_NAME VARCHAR(128) NOT NULL,
    GRAY_RULE CLOB NOT NULL,
    ENCRYPTED_DATA_KEY VARCHAR(256) NOT NULL DEFAULT ''
);

-- 主键和索引
ALTER TABLE CONFIG_INFO_GRAY ADD CONSTRAINT PK_CONFIG_INFO_GRAY PRIMARY KEY (ID);
CREATE UNIQUE INDEX UK_CONFIGINFOGRAY_DATAGROUPTENANTGRAY ON CONFIG_INFO_GRAY (DATA_ID, GROUP_ID, TENANT_ID, GRAY_NAME);
CREATE INDEX IDX_DATAID_GMT_MODIFIED_CI ON CONFIG_INFO_GRAY (DATA_ID, GMT_MODIFIED); -- 后缀_CI避免重复
CREATE INDEX IDX_GMT_MODIFIED_CI ON CONFIG_INFO_GRAY (GMT_MODIFIED); -- 后缀_CI避免重复

-- 表注释和列注释
COMMENT ON TABLE CONFIG_INFO_GRAY IS 'config_info_gray';
COMMENT ON COLUMN CONFIG_INFO_GRAY.ID IS 'id';
COMMENT ON COLUMN CONFIG_INFO_GRAY.DATA_ID IS 'data_id';
COMMENT ON COLUMN CONFIG_INFO_GRAY.GROUP_ID IS 'group_id';
COMMENT ON COLUMN CONFIG_INFO_GRAY.CONTENT IS 'content';
COMMENT ON COLUMN CONFIG_INFO_GRAY.MD5 IS 'md5';
COMMENT ON COLUMN CONFIG_INFO_GRAY.SRC_USER IS 'src_user';
COMMENT ON COLUMN CONFIG_INFO_GRAY.SRC_IP IS 'src_ip';
COMMENT ON COLUMN CONFIG_INFO_GRAY.GMT_CREATE IS 'gmt_create';
COMMENT ON COLUMN CONFIG_INFO_GRAY.GMT_MODIFIED IS 'gmt_modified';
COMMENT ON COLUMN CONFIG_INFO_GRAY.APP_NAME IS 'app_name';
COMMENT ON COLUMN CONFIG_INFO_GRAY.TENANT_ID IS 'tenant_id';
COMMENT ON COLUMN CONFIG_INFO_GRAY.GRAY_NAME IS 'gray_name';
COMMENT ON COLUMN CONFIG_INFO_GRAY.GRAY_RULE IS 'gray_rule';
COMMENT ON COLUMN CONFIG_INFO_GRAY.ENCRYPTED_DATA_KEY IS 'encrypted_data_key';

/******************************************/
/*   表名称 = CONFIG_TAGS_RELATION         */
/******************************************/
CREATE TABLE CONFIG_TAGS_RELATION (
    ID BIGINT NOT NULL,
    TAG_NAME VARCHAR(128) NOT NULL,
    TAG_TYPE VARCHAR(64) DEFAULT NULL,
    DATA_ID VARCHAR(255) NOT NULL,
    GROUP_ID VARCHAR(128) NOT NULL,
    TENANT_ID VARCHAR(128) DEFAULT '',
    NID BIGINT NOT NULL IDENTITY(1,1)
);

-- 主键和索引
ALTER TABLE CONFIG_TAGS_RELATION ADD CONSTRAINT PK_CONFIG_TAGS_RELATION PRIMARY KEY (NID);
CREATE UNIQUE INDEX UK_CONFIGTAGRELATION_CONFIGIDTAG ON CONFIG_TAGS_RELATION (ID, TAG_NAME, TAG_TYPE);
CREATE INDEX IDX_TENANT_ID_CTR ON CONFIG_TAGS_RELATION (TENANT_ID); -- 后缀_CTR避免重复

-- 表注释和列注释
COMMENT ON TABLE CONFIG_TAGS_RELATION IS 'config_tag_relation';
COMMENT ON COLUMN CONFIG_TAGS_RELATION.ID IS 'id';
COMMENT ON COLUMN CONFIG_TAGS_RELATION.TAG_NAME IS 'tag_name';
COMMENT ON COLUMN CONFIG_TAGS_RELATION.TAG_TYPE IS 'tag_type';
COMMENT ON COLUMN CONFIG_TAGS_RELATION.DATA_ID IS 'data_id';
COMMENT ON COLUMN CONFIG_TAGS_RELATION.GROUP_ID IS 'group_id';
COMMENT ON COLUMN CONFIG_TAGS_RELATION.TENANT_ID IS 'tenant_id';
COMMENT ON COLUMN CONFIG_TAGS_RELATION.NID IS 'nid, 自增长标识';

/******************************************/
/*   表名称 = GROUP_CAPACITY               */
/******************************************/
CREATE TABLE GROUP_CAPACITY (
    ID BIGINT NOT NULL IDENTITY(1,1),
    GROUP_ID VARCHAR(128) NOT NULL DEFAULT '',
    QUOTA INT NOT NULL DEFAULT 0,
    USAGE INT NOT NULL DEFAULT 0,
    MAX_SIZE INT NOT NULL DEFAULT 0,
    MAX_AGGR_COUNT INT NOT NULL DEFAULT 0,
    MAX_AGGR_SIZE INT NOT NULL DEFAULT 0,
    MAX_HISTORY_COUNT INT NOT NULL DEFAULT 0,
    GMT_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    GMT_MODIFIED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 主键和索引
ALTER TABLE GROUP_CAPACITY ADD CONSTRAINT PK_GROUP_CAPACITY PRIMARY KEY (ID);
CREATE UNIQUE INDEX UK_GROUP_ID_GC ON GROUP_CAPACITY (GROUP_ID); -- 后缀_GC避免重复

-- 表注释和列注释
COMMENT ON TABLE GROUP_CAPACITY IS '集群、各Group容量信息表';
COMMENT ON COLUMN GROUP_CAPACITY.ID IS '主键ID';
COMMENT ON COLUMN GROUP_CAPACITY.GROUP_ID IS 'Group ID，空字符表示整个集群';
COMMENT ON COLUMN GROUP_CAPACITY.QUOTA IS '配额，0表示使用默认值';
COMMENT ON COLUMN GROUP_CAPACITY.USAGE IS '使用量';
COMMENT ON COLUMN GROUP_CAPACITY.MAX_SIZE IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN GROUP_CAPACITY.MAX_AGGR_COUNT IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN GROUP_CAPACITY.MAX_AGGR_SIZE IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN GROUP_CAPACITY.MAX_HISTORY_COUNT IS '最大变更历史数量';
COMMENT ON COLUMN GROUP_CAPACITY.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN GROUP_CAPACITY.GMT_MODIFIED IS '修改时间';

/******************************************/
/*   表名称 = HIS_CONFIG_INFO              */
/******************************************/
CREATE TABLE HIS_CONFIG_INFO (
    ID BIGINT NOT NULL,
    NID BIGINT NOT NULL IDENTITY(1,1),
    DATA_ID VARCHAR(255) NOT NULL,
    GROUP_ID VARCHAR(128) NOT NULL,
    APP_NAME VARCHAR(128) DEFAULT NULL,
    CONTENT CLOB NOT NULL,
    MD5 VARCHAR(32) DEFAULT NULL,
    GMT_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    GMT_MODIFIED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SRC_USER CLOB,
    SRC_IP VARCHAR(50) DEFAULT NULL,
    OP_TYPE CHAR(10) DEFAULT NULL,
    TENANT_ID VARCHAR(128) DEFAULT '',
    ENCRYPTED_DATA_KEY VARCHAR(1024) NOT NULL DEFAULT '',
    PUBLISH_TYPE VARCHAR(50) DEFAULT 'formal',
    GRAY_NAME VARCHAR(128) DEFAULT NULL,
    EXT_INFO CLOB DEFAULT NULL
);

-- 主键和索引
ALTER TABLE HIS_CONFIG_INFO ADD CONSTRAINT PK_HIS_CONFIG_INFO PRIMARY KEY (NID);
CREATE INDEX IDX_GMT_CREATE_HCI ON HIS_CONFIG_INFO (GMT_CREATE); -- 后缀_HCI避免重复
CREATE INDEX IDX_GMT_MODIFIED_HCI ON HIS_CONFIG_INFO (GMT_MODIFIED); -- 后缀_HCI避免重复
CREATE INDEX IDX_DID_HCI ON HIS_CONFIG_INFO (DATA_ID); -- 后缀_HCI避免重复

-- 表注释和列注释
COMMENT ON TABLE HIS_CONFIG_INFO IS '多租户改造';
COMMENT ON COLUMN HIS_CONFIG_INFO.ID IS 'id';
COMMENT ON COLUMN HIS_CONFIG_INFO.NID IS 'nid, 自增标识';
COMMENT ON COLUMN HIS_CONFIG_INFO.DATA_ID IS 'data_id';
COMMENT ON COLUMN HIS_CONFIG_INFO.GROUP_ID IS 'group_id';
COMMENT ON COLUMN HIS_CONFIG_INFO.APP_NAME IS 'app_name';
COMMENT ON COLUMN HIS_CONFIG_INFO.CONTENT IS 'content';
COMMENT ON COLUMN HIS_CONFIG_INFO.MD5 IS 'md5';
COMMENT ON COLUMN HIS_CONFIG_INFO.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN HIS_CONFIG_INFO.GMT_MODIFIED IS '修改时间';
COMMENT ON COLUMN HIS_CONFIG_INFO.SRC_USER IS 'source user';
COMMENT ON COLUMN HIS_CONFIG_INFO.SRC_IP IS 'source ip';
COMMENT ON COLUMN HIS_CONFIG_INFO.OP_TYPE IS 'operation type';
COMMENT ON COLUMN HIS_CONFIG_INFO.TENANT_ID IS '租户字段';
COMMENT ON COLUMN HIS_CONFIG_INFO.ENCRYPTED_DATA_KEY IS '密钥';
COMMENT ON COLUMN HIS_CONFIG_INFO.PUBLISH_TYPE IS 'publish type gray or formal';
COMMENT ON COLUMN HIS_CONFIG_INFO.GRAY_NAME IS 'gray_name';
COMMENT ON COLUMN HIS_CONFIG_INFO.EXT_INFO IS 'ext info';

/******************************************/
/*   表名称 = TENANT_CAPACITY              */
/******************************************/
CREATE TABLE TENANT_CAPACITY (
    ID BIGINT NOT NULL IDENTITY(1,1),
    TENANT_ID VARCHAR(128) NOT NULL DEFAULT '',
    QUOTA INT NOT NULL DEFAULT 0,
    USAGE INT NOT NULL DEFAULT 0,
    MAX_SIZE INT NOT NULL DEFAULT 0,
    MAX_AGGR_COUNT INT NOT NULL DEFAULT 0,
    MAX_AGGR_SIZE INT NOT NULL DEFAULT 0,
    MAX_HISTORY_COUNT INT NOT NULL DEFAULT 0,
    GMT_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    GMT_MODIFIED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 主键和索引
ALTER TABLE TENANT_CAPACITY ADD CONSTRAINT PK_TENANT_CAPACITY PRIMARY KEY (ID);
CREATE UNIQUE INDEX UK_TENANT_ID_TC ON TENANT_CAPACITY (TENANT_ID); -- 后缀_TC避免重复

-- 表注释和列注释
COMMENT ON TABLE TENANT_CAPACITY IS '租户容量信息表';
COMMENT ON COLUMN TENANT_CAPACITY.ID IS '主键ID';
COMMENT ON COLUMN TENANT_CAPACITY.TENANT_ID IS 'Tenant ID';
COMMENT ON COLUMN TENANT_CAPACITY.QUOTA IS '配额，0表示使用默认值';
COMMENT ON COLUMN TENANT_CAPACITY.USAGE IS '使用量';
COMMENT ON COLUMN TENANT_CAPACITY.MAX_SIZE IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN TENANT_CAPACITY.MAX_AGGR_COUNT IS '聚合子配置最大个数';
COMMENT ON COLUMN TENANT_CAPACITY.MAX_AGGR_SIZE IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN TENANT_CAPACITY.MAX_HISTORY_COUNT IS '最大变更历史数量';
COMMENT ON COLUMN TENANT_CAPACITY.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN TENANT_CAPACITY.GMT_MODIFIED IS '修改时间';

/******************************************/
/*   表名称 = TENANT_INFO                  */
/******************************************/
CREATE TABLE TENANT_INFO (
    ID BIGINT NOT NULL IDENTITY(1,1),
    KP VARCHAR(128) NOT NULL,
    TENANT_ID VARCHAR(128) DEFAULT '',
    TENANT_NAME VARCHAR(128) DEFAULT '',
    TENANT_DESC VARCHAR(256) DEFAULT NULL,
    CREATE_SOURCE VARCHAR(32) DEFAULT NULL,
    GMT_CREATE BIGINT NOT NULL,
    GMT_MODIFIED BIGINT NOT NULL
);

-- 主键和索引
ALTER TABLE TENANT_INFO ADD CONSTRAINT PK_TENANT_INFO PRIMARY KEY (ID);
CREATE UNIQUE INDEX UK_TENANT_INFO_KPTENANTID ON TENANT_INFO (KP, TENANT_ID);
CREATE INDEX IDX_TENANT_ID_TI ON TENANT_INFO (TENANT_ID); -- 后缀_TI避免重复

-- 表注释和列注释
COMMENT ON TABLE TENANT_INFO IS 'tenant_info';
COMMENT ON COLUMN TENANT_INFO.ID IS 'id';
COMMENT ON COLUMN TENANT_INFO.KP IS 'kp';
COMMENT ON COLUMN TENANT_INFO.TENANT_ID IS 'tenant_id';
COMMENT ON COLUMN TENANT_INFO.TENANT_NAME IS 'tenant_name';
COMMENT ON COLUMN TENANT_INFO.TENANT_DESC IS 'tenant_desc';
COMMENT ON COLUMN TENANT_INFO.CREATE_SOURCE IS 'create_source';
COMMENT ON COLUMN TENANT_INFO.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN TENANT_INFO.GMT_MODIFIED IS '修改时间';

/******************************************/
/*   表名称 = USERS                        */
/******************************************/
CREATE TABLE USERS (
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(500) NOT NULL,
    ENABLED BIT NOT NULL
);

-- 主键
ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (USERNAME);

-- 表注释和列注释
COMMENT ON TABLE USERS IS '用户表';
COMMENT ON COLUMN USERS.USERNAME IS 'username';
COMMENT ON COLUMN USERS.PASSWORD IS 'password';
COMMENT ON COLUMN USERS.ENABLED IS 'enabled';

/******************************************/
/*   表名称 = ROLES                        */
/******************************************/
CREATE TABLE ROLES (
    USERNAME VARCHAR(50) NOT NULL,
    ROLE VARCHAR(50) NOT NULL
);

-- 索引（唯一索引）
CREATE UNIQUE INDEX IDX_USER_ROLE_ROLES ON ROLES (USERNAME, ROLE); -- 后缀_ROLES避免重复

-- 表注释和列注释
COMMENT ON TABLE ROLES IS '角色表';
COMMENT ON COLUMN ROLES.USERNAME IS 'username';
COMMENT ON COLUMN ROLES.ROLE IS 'role';

/******************************************/
/*   表名称 = PERMISSIONS                  */
/******************************************/
CREATE TABLE PERMISSIONS (
    ROLE VARCHAR(50) NOT NULL,
    RESOURCE VARCHAR(128) NOT NULL,
    ACTION VARCHAR(8) NOT NULL
);

-- 索引（唯一索引）
CREATE UNIQUE INDEX UK_ROLE_PERMISSION_PERM ON PERMISSIONS (ROLE, RESOURCE, ACTION); -- 后缀_PERM避免重复

-- 表注释和列注释
COMMENT ON TABLE PERMISSIONS IS '权限表';
COMMENT ON COLUMN PERMISSIONS.ROLE IS 'role';
COMMENT ON COLUMN PERMISSIONS.RESOURCE IS 'resource';
COMMENT ON COLUMN PERMISSIONS.ACTION IS 'action';