/*
 * Copyright 1999-2023 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 -- ----------------------------
 -- sequence for tables
 -- ----------------------------
CREATE SEQUENCE "GROUP_CAPACITY_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "CONFIG_INFO_AGGR_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "CONFIG_INFO_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "CONFIG_INFO_BETA_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "CONFIG_INFO_TAG_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "CONFIG_TAGS_RELATION_NID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "TENANT_CAPACITY_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "HIS_CONFIG_INFO_NID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "TENANT_INFO_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "CONFIG_INFO_GRAY_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "AI_RESOURCE_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "AI_RESOURCE_VERSION_ID_SEQ" INCREMENT BY 1 START WITH 1;
-- ----------------------------
-- Table structure for config_info
-- ----------------------------
CREATE TABLE "CONFIG_TAGS_RELATION" (
	"ID" BIGINT NOT NULL,
	"TAG_NAME" VARCHAR(128 CHAR) NOT NULL,
	"TAG_TYPE" VARCHAR(64 CHAR) DEFAULT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) NOT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	"NID" BIGINT DEFAULT "CONFIG_TAGS_RELATION_NID_SEQ".NEXTVAL  NOT NULL,
	PRIMARY KEY ("NID")
);
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TAG_NAME" IS 'tag_name';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TAG_TYPE" IS 'tag_type';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TENANT_ID" IS 'tenant_id';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."NID" IS 'nid, 自增长标识';
COMMENT ON TABLE "CONFIG_TAGS_RELATION" IS 'config_tag_relation';

-- ----------------------------
-- Table structure for CONFIG_INFO_TAG
-- ----------------------------
CREATE TABLE "CONFIG_INFO_TAG" (
	"ID" BIGINT DEFAULT "CONFIG_INFO_TAG_ID_SEQ".NEXTVAL  NOT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) NOT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	"TAG_ID" VARCHAR(128 CHAR) NOT NULL,
	"APP_NAME" VARCHAR(128 CHAR) DEFAULT NULL,
	"CONTENT" CLOB NOT NULL,
	"MD5" VARCHAR(32 CHAR) DEFAULT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"SRC_USER" CLOB,
	"SRC_IP" VARCHAR(50 CHAR) DEFAULT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "CONFIG_INFO_TAG"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."TENANT_ID" IS 'tenant_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."TAG_ID" IS 'tag_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."CONTENT" IS 'content';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."MD5" IS 'md5';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."SRC_IP" IS 'source ip';
COMMENT ON TABLE "CONFIG_INFO_TAG" IS 'config_info_tag';

-- ----------------------------
-- Table structure for CONFIG_INFO_BETA
-- ----------------------------
CREATE TABLE "CONFIG_INFO_BETA" (
	"ID" BIGINT DEFAULT "CONFIG_INFO_BETA_ID_SEQ".NEXTVAL  NOT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) NOT NULL,
	"APP_NAME" VARCHAR(128 CHAR) DEFAULT NULL,
	"CONTENT" CLOB NOT NULL,
	"BETA_IPS" VARCHAR(1024 CHAR) DEFAULT NULL,
	"MD5" VARCHAR(32 CHAR) DEFAULT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"SRC_USER" CLOB,
	"SRC_IP" VARCHAR(50 CHAR) DEFAULT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	"ENCRYPTED_DATA_KEY" VARCHAR(1024 CHAR) DEFAULT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "CONFIG_INFO_BETA"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."CONTENT" IS 'content';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."BETA_IPS" IS 'betaIps';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."MD5" IS 'md5';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."SRC_IP" IS 'source ip';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."ENCRYPTED_DATA_KEY" IS '密钥';
COMMENT ON TABLE "CONFIG_INFO_BETA" IS 'config_info_beta';


-- ----------------------------
-- Table structure for CONFIG_INFO_AGGR
-- ----------------------------
CREATE TABLE "CONFIG_INFO_AGGR" (
	"ID" BIGINT DEFAULT "CONFIG_INFO_AGGR_ID_SEQ".NEXTVAL  NOT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) NOT NULL,
	"DATUM_ID" VARCHAR(255 CHAR) NOT NULL,
	"CONTENT" CLOB NOT NULL,
	"GMT_MODIFIED" TIMESTAMP NOT NULL,
	"APP_NAME" VARCHAR(128 CHAR) DEFAULT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."DATUM_ID" IS 'datum_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."CONTENT" IS '内容';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."TENANT_ID" IS '租户字段';
COMMENT ON TABLE "CONFIG_INFO_AGGR" IS '增加租户字段';

-- ----------------------------
-- Table structure for CONFIG_INFO
-- ----------------------------
CREATE TABLE "CONFIG_INFO" (
	"ID" BIGINT DEFAULT "CONFIG_INFO_ID_SEQ".NEXTVAL  NOT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) DEFAULT NULL,
	"CONTENT" CLOB NOT NULL,
	"MD5" VARCHAR(32 CHAR) DEFAULT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"SRC_USER" CLOB,
	"SRC_IP" VARCHAR(50 CHAR) DEFAULT NULL,
	"APP_NAME" VARCHAR(128 CHAR) DEFAULT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT 'PUBLIC',
	"C_DESC" VARCHAR(256 CHAR) DEFAULT NULL,
	"C_USE" VARCHAR(64 CHAR) DEFAULT NULL,
	"EFFECT" VARCHAR(64 CHAR) DEFAULT NULL,
	"TYPE" VARCHAR(64 CHAR) DEFAULT NULL,
	"C_SCHEMA" CLOB,
	"ENCRYPTED_DATA_KEY" VARCHAR(1024 CHAR) DEFAULT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "CONFIG_INFO"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO"."CONTENT" IS 'content';
COMMENT ON COLUMN "CONFIG_INFO"."MD5" IS 'md5';
COMMENT ON COLUMN "CONFIG_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "CONFIG_INFO"."SRC_IP" IS 'source ip';
COMMENT ON COLUMN "CONFIG_INFO"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "CONFIG_INFO"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "CONFIG_INFO"."C_DESC" IS 'configuration description';
COMMENT ON COLUMN "CONFIG_INFO"."C_USE" IS 'configuration usage';
COMMENT ON COLUMN "CONFIG_INFO"."EFFECT" IS '配置生效的描述';
COMMENT ON COLUMN "CONFIG_INFO"."TYPE" IS '配置的类型';
COMMENT ON COLUMN "CONFIG_INFO"."C_SCHEMA" IS '配置的模式';
COMMENT ON COLUMN "CONFIG_INFO"."ENCRYPTED_DATA_KEY" IS '密钥';
COMMENT ON TABLE "CONFIG_INFO" IS 'config_info';

-- ----------------------------
-- Table structure for PERMISSIONS
-- ----------------------------
CREATE TABLE "PERMISSIONS" (
	"ROLE" VARCHAR(50 CHAR) NOT NULL,
	"RESOURCE" VARCHAR(128 CHAR) NOT NULL,
	"ACTION" VARCHAR(8 CHAR) NOT NULL
);
COMMENT ON COLUMN "PERMISSIONS"."ROLE" IS 'role';
COMMENT ON COLUMN "PERMISSIONS"."RESOURCE" IS 'resource';
COMMENT ON COLUMN "PERMISSIONS"."ACTION" IS 'action';

-- ----------------------------
-- Table structure for ROLES
-- ----------------------------
CREATE TABLE "ROLES" (
	"USERNAME" VARCHAR(50 CHAR) NOT NULL,
	"ROLE" VARCHAR(50 CHAR) NOT NULL
);
COMMENT ON COLUMN "ROLES"."USERNAME" IS 'username';
COMMENT ON COLUMN "ROLES"."ROLE" IS 'role';

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
CREATE TABLE "USERS" (
	"USERNAME" VARCHAR(50 CHAR) NOT NULL PRIMARY KEY,
	"PASSWORD" VARCHAR(500 CHAR) NOT NULL,
	"ENABLED" BOOLEAN NOT NULL
);
COMMENT ON COLUMN "USERS"."USERNAME" IS 'username';
COMMENT ON COLUMN "USERS"."PASSWORD" IS 'password';
COMMENT ON COLUMN "USERS"."ENABLED" IS 'enabled';

-- ----------------------------
-- Table structure for TENANT_INFO
-- ----------------------------
CREATE TABLE "TENANT_INFO" (
	"ID" BIGINT DEFAULT "TENANT_INFO_ID_SEQ".NEXTVAL  NOT NULL,
	"KP" VARCHAR(128 CHAR) NOT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	"TENANT_NAME" VARCHAR(128 CHAR) DEFAULT '',
	"TENANT_DESC" VARCHAR(256 CHAR) DEFAULT NULL,
	"CREATE_SOURCE" VARCHAR(32 CHAR) DEFAULT NULL,
	"GMT_CREATE" BIGINT NOT NULL,
	"GMT_MODIFIED" BIGINT NOT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "TENANT_INFO"."ID" IS 'id';
COMMENT ON COLUMN "TENANT_INFO"."KP" IS 'kp';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_ID" IS 'tenant_id';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_NAME" IS 'tenant_name';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_DESC" IS 'tenant_desc';
COMMENT ON COLUMN "TENANT_INFO"."CREATE_SOURCE" IS 'create_source';
COMMENT ON COLUMN "TENANT_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "TENANT_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "TENANT_INFO" IS 'tenant_info';

-- ----------------------------
-- Table structure for TENANT_CAPACITY
-- ----------------------------
CREATE TABLE "TENANT_CAPACITY" (
	"ID" NUMBER DEFAULT "TENANT_CAPACITY_ID_SEQ".NEXTVAL  NOT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '' NOT NULL,
	"QUOTA" BIGINT DEFAULT '0' NOT NULL,
	"USAGE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_SIZE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_AGGR_COUNT" BIGINT DEFAULT '0' NOT NULL,
	"MAX_AGGR_SIZE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_HISTORY_COUNT" BIGINT DEFAULT '0' NOT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "TENANT_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "TENANT_CAPACITY"."TENANT_ID" IS 'Tenant ID';
COMMENT ON COLUMN "TENANT_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "TENANT_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "TENANT_CAPACITY"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "TENANT_CAPACITY" IS '租户容量信息表';

-- ----------------------------
-- Table structure for HIS_CONFIG_INFO
-- ----------------------------
CREATE TABLE "HIS_CONFIG_INFO" (
	"ID" NUMBER NOT NULL,
	"NID" NUMBER DEFAULT "HIS_CONFIG_INFO_NID_SEQ".NEXTVAL  NOT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) NOT NULL,
	"APP_NAME" VARCHAR(128 CHAR) DEFAULT NULL,
	"CONTENT" CLOB NOT NULL,
	"MD5" VARCHAR(32 CHAR) DEFAULT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"SRC_USER" CLOB,
	"SRC_IP" VARCHAR(50 CHAR) DEFAULT NULL,
	"OP_TYPE" CHAR(10 CHAR) DEFAULT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	"ENCRYPTED_DATA_KEY" VARCHAR(1024 CHAR) DEFAULT NULL,
	"PUBLISH_TYPE" VARCHAR(50)  DEFAULT 'FORMAL',
    "GRAY_NAME" VARCHAR(50)  DEFAULT NULL,
    "EXT_INFO"  CLOB DEFAULT NULL,
	PRIMARY KEY ("NID")
);
COMMENT ON COLUMN "HIS_CONFIG_INFO"."ID" IS 'id';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."NID" IS 'nid, 自增标识';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."CONTENT" IS 'content';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."MD5" IS 'md5';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."SRC_IP" IS 'source ip';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."OP_TYPE" IS 'operation type';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."ENCRYPTED_DATA_KEY" IS '密钥';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."PUBLISH_TYPE" IS 'publish type gray or formal';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."GRAY_NAME" IS 'gray name';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."EXT_INFO" IS 'EXT INFO';
COMMENT ON TABLE "HIS_CONFIG_INFO" IS '多租户改造';

-- ----------------------------
-- Table structure for GROUP_CAPACITY
-- ----------------------------
CREATE TABLE "GROUP_CAPACITY" (
	"ID" NUMBER DEFAULT "GROUP_CAPACITY_ID_SEQ".NEXTVAL  NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) DEFAULT '' NOT NULL,
	"QUOTA" BIGINT DEFAULT '0' NOT NULL,
	"USAGE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_SIZE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_AGGR_COUNT" BIGINT DEFAULT '0' NOT NULL,
	"MAX_AGGR_SIZE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_HISTORY_COUNT" BIGINT DEFAULT '0' NOT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "GROUP_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "GROUP_CAPACITY"."GROUP_ID" IS 'Group ID，空字符表示整个集群';
COMMENT ON COLUMN "GROUP_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "GROUP_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "GROUP_CAPACITY"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "GROUP_CAPACITY" IS '集群、各Group容量信息表';


-- ----------------------------
-- Table index for tables
-- ----------------------------

CREATE UNIQUE INDEX "UK_CONFIGINFO_DATAGROUPTENANT" ON "CONFIG_INFO"("DATA_ID", "GROUP_ID", "TENANT_ID");

CREATE UNIQUE INDEX "UK_CONFIGINFOAGGR_DATAGROUPTENANTDATUM" ON "CONFIG_INFO_AGGR"("DATA_ID", "GROUP_ID", "TENANT_ID", "DATUM_ID");

CREATE UNIQUE INDEX "UK_CONFIGINFOBETA_DATAGROUPTENANT" ON "CONFIG_INFO_BETA"("DATA_ID", "GROUP_ID", "TENANT_ID");

CREATE UNIQUE INDEX "UK_CONFIGINFOTAG_DATAGROUPTENANTTAG" ON "CONFIG_INFO_TAG"("DATA_ID", "GROUP_ID", "TENANT_ID", "TAG_ID");

CREATE UNIQUE INDEX "UK_CONFIGTAGRELATION_CONFIGIDTAG" ON "CONFIG_TAGS_RELATION"("ID", "TAG_NAME", "TAG_TYPE");

CREATE INDEX "IDX_TENANT_ID" ON "CONFIG_TAGS_RELATION"("TENANT_ID");

CREATE INDEX "IDX_DID" ON "HIS_CONFIG_INFO"("DATA_ID");

CREATE INDEX "IDX_GMT_MODIFIED" ON "HIS_CONFIG_INFO"("GMT_MODIFIED");

CREATE INDEX "IDX_GMT_CREATE" ON "HIS_CONFIG_INFO"("GMT_CREATE");

CREATE UNIQUE INDEX "UK_GROUP_ID" ON "GROUP_CAPACITY"("GROUP_ID");

CREATE UNIQUE INDEX "UK_TENANT_ID" ON "TENANT_CAPACITY"("TENANT_ID");

CREATE UNIQUE INDEX "UK_TENANT_INFO_KPTENANTID" ON "TENANT_INFO"("KP", "TENANT_ID");

CREATE UNIQUE INDEX "IDX_USER_ROLE" ON "ROLES"("USERNAME" ASC, "ROLE" ASC);

CREATE UNIQUE INDEX "UK_ROLE_PERMISSION" ON "PERMISSIONS"("ROLE", "RESOURCE", "ACTION");

-- ----------------------------
-- Table structure for CONFIG_INFO_GRAY
-- ----------------------------
CREATE TABLE "CONFIG_INFO_GRAY"
(
    "ID"                 NUMBER                DEFAULT "CONFIG_INFO_GRAY_ID_SEQ".NEXTVAL NOT NULL,
    "DATA_ID"            VARCHAR(255) NOT NULL,
    "GROUP_ID"           VARCHAR(128) NOT NULL,
    "CONTENT"            CLOB         NOT NULL,
    "MD5"                VARCHAR(32)           DEFAULT NULL,
    "SRC_USER"           CLOB,
    "SRC_IP"             VARCHAR(100)          DEFAULT NULL,
    "GMT_CREATE"         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "GMT_MODIFIED"       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "APP_NAME"           VARCHAR(128)          DEFAULT NULL,
    "TENANT_ID"          VARCHAR(128)          DEFAULT '',
    "GRAY_NAME"          VARCHAR(128) NOT NULL,
    "GRAY_RULE"          CLOB         NOT NULL,
    "ENCRYPTED_DATA_KEY" VARCHAR(256) NOT NULL DEFAULT '',
    PRIMARY KEY ("ID"),
);

CREATE UNIQUE INDEX "UK_CONFIGINFOGRAY_DATAGROUPTENANTGRAY" ON "CONFIG_INFO_GRAY"("DATA_ID", "GROUP_ID", "TENANT_ID","GRAY_NAME");
CREATE INDEX "IDX_DATAID_GMT_MODIFIED" ON "CONFIG_INFO_GRAY"("DATA_ID","GMT_MODIFIED");
CREATE INDEX "IDX_GMT_MODIFIED_GRAY" ON "CONFIG_INFO_GRAY"("GMT_MODIFIED");

-- ----------------------------
-- Table structure for PIPELINE_EXECUTION since 3.2.0
-- ----------------------------
CREATE TABLE "PIPELINE_EXECUTION" (
    "EXECUTION_ID"  VARCHAR(64)  NOT NULL,
    "RESOURCE_TYPE" VARCHAR(32)  NOT NULL,
    "RESOURCE_NAME" VARCHAR(256) NOT NULL,
    "NAMESPACE_ID"  VARCHAR(128) DEFAULT NULL,
    "VERSION"       VARCHAR(64)  DEFAULT NULL,
    "STATUS"        VARCHAR(32)  NOT NULL,
    "PIPELINE"      CLOB     NOT NULL,
    "CREATE_TIME"   NUMBER   NOT NULL,
    "UPDATE_TIME"   NUMBER   NOT NULL,
    PRIMARY KEY ("EXECUTION_ID")
);

COMMENT ON TABLE "PIPELINE_EXECUTION" IS 'AI资源发布审核Pipeline执行记录';
COMMENT ON COLUMN "PIPELINE_EXECUTION"."EXECUTION_ID" IS '执行ID';
COMMENT ON COLUMN "PIPELINE_EXECUTION"."RESOURCE_TYPE" IS '资源类型';
COMMENT ON COLUMN "PIPELINE_EXECUTION"."RESOURCE_NAME" IS '资源名称';
COMMENT ON COLUMN "PIPELINE_EXECUTION"."NAMESPACE_ID" IS '命名空间ID';
COMMENT ON COLUMN "PIPELINE_EXECUTION"."VERSION" IS '版本';
COMMENT ON COLUMN "PIPELINE_EXECUTION"."STATUS" IS '执行状态';
COMMENT ON COLUMN "PIPELINE_EXECUTION"."PIPELINE" IS 'PIPELINE节点结果JSON';
COMMENT ON COLUMN "PIPELINE_EXECUTION"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "PIPELINE_EXECUTION"."UPDATE_TIME" IS '修改时间';


-- ----------------------------
-- Table structure for AI_RESOURCE since 3.2.0
-- ----------------------------
CREATE TABLE "AI_RESOURCE"
(
    "ID"             NUMBER                DEFAULT "AI_RESOURCE_ID_SEQ".NEXTVAL NOT NULL,
    "GMT_CREATE"     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "GMT_MODIFIED"   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "NAME"           VARCHAR(256) NOT NULL,
    "TYPE"           VARCHAR(32)  NOT NULL,
    "C_DESC"         VARCHAR(2048)         DEFAULT NULL,
    "STATUS"         VARCHAR(32)           DEFAULT NULL,
    "NAMESPACE_ID"   VARCHAR(128) NOT NULL DEFAULT '',
    "BIZ_TAGS"       VARCHAR(1024)         DEFAULT NULL,
    "EXT"            CLOB                  DEFAULT NULL,
    "C_FROM"         VARCHAR(256) NOT NULL DEFAULT 'LOCAL',
    "VERSION_INFO"   CLOB                  DEFAULT NULL,
    "META_VERSION"   NUMBER       NOT NULL DEFAULT '1',
    "SCOPE"          VARCHAR(16)  NOT NULL DEFAULT 'PRIVATE',
    "OWNER"          VARCHAR(128) NOT NULL DEFAULT '',
    "DOWNLOAD_COUNT" NUMBER       NOT NULL DEFAULT '0',
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "AI_RESOURCE" IS 'AI资源元数据表';
COMMENT ON COLUMN "AI_RESOURCE"."ID" IS 'ID';
COMMENT ON COLUMN "AI_RESOURCE"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "AI_RESOURCE"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "AI_RESOURCE"."NAME" IS '资源名称';
COMMENT ON COLUMN "AI_RESOURCE"."TYPE" IS '资源类型';
COMMENT ON COLUMN "AI_RESOURCE"."C_DESC" IS '资源描述';
COMMENT ON COLUMN "AI_RESOURCE"."STATUS" IS '资源状态';
COMMENT ON COLUMN "AI_RESOURCE"."NAMESPACE_ID" IS '命名空间ID';
COMMENT ON COLUMN "AI_RESOURCE"."BIZ_TAGS" IS '业务标签';
COMMENT ON COLUMN "AI_RESOURCE"."EXT" IS '扩展信息(JSON)';
COMMENT ON COLUMN "AI_RESOURCE"."C_FROM" IS '来源标识(导入/同步来源)';
COMMENT ON COLUMN "AI_RESOURCE"."VERSION_INFO" IS '版本信息(JSON)';
COMMENT ON COLUMN "AI_RESOURCE"."META_VERSION" IS '元数据版本(乐观锁)';
COMMENT ON COLUMN "AI_RESOURCE"."SCOPE" IS '可见性: PUBLIC/PRIVATE';
COMMENT ON COLUMN "AI_RESOURCE"."OWNER" IS '创建者用户名';
COMMENT ON COLUMN "AI_RESOURCE"."DOWNLOAD_COUNT" IS '下载次数';

CREATE UNIQUE INDEX "UK_AI_RESOURCE_NS_NAME_TYPE" ON "AI_RESOURCE"("NAMESPACE_ID", "NAME", "TYPE", "C_FROM");
CREATE INDEX "IDX_AI_RESOURCE_NAME" ON "AI_RESOURCE"("NAME");
CREATE INDEX "IDX_AI_RESOURCE_TYPE" ON "AI_RESOURCE"("TYPE");
CREATE INDEX "IDX_AI_RESOURCE_GMT_MODIFIED" ON "AI_RESOURCE"("GMT_MODIFIED");


-- ----------------------------
-- Table structure for AI_RESOURCE_VERSION since 3.2.0
-- ----------------------------
CREATE TABLE "AI_RESOURCE_VERSION"
(
    "ID"                    NUMBER                DEFAULT "AI_RESOURCE_VERSION_ID_SEQ".NEXTVAL NOT NULL,
    "GMT_CREATE"            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "GMT_MODIFIED"          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TYPE"                  VARCHAR(32)  NOT NULL,
    "AUTHOR"                VARCHAR(256) NOT NULL,
    "NAME"                  VARCHAR(256) NOT NULL,
    "C_DESC"                VARCHAR(2048)         DEFAULT NULL,
    "STATUS"                VARCHAR(32)           DEFAULT NULL,
    "VERSION"               varchar(64)  NOT NULL,
    "NAMESPACE_ID"          VARCHAR(128) NOT NULL DEFAULT '',
    "STORAGE"               CLOB                  DEFAULT NULL,
    "PUBLISH_PIPELINE_INFO" CLOB                  DEFAULT NULL,
    "DOWNLOAD_COUNT"        NUMBER       NOT NULL DEFAULT '0',
    PRIMARY KEY ("ID")
);

COMMENT ON TABLE "AI_RESOURCE_VERSION" IS 'AI资源版本表';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."ID" IS 'ID';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."TYPE" IS '资源类型';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."AUTHOR" IS '作者';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."NAME" IS '资源名称';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."C_DESC" IS '资源描述';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."STATUS" IS '资源状态';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."VERSION" IS '版本号';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."NAMESPACE_ID" IS '命名空间ID';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."DOWNLOAD_COUNT" IS '存储信息(JSON)';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."DOWNLOAD_COUNT" IS '发布流水线信息(JSON)';
COMMENT ON COLUMN "AI_RESOURCE_VERSION"."DOWNLOAD_COUNT" IS '下载次数';


CREATE UNIQUE INDEX "UK_AI_RESOURCE_VER_NS_NAME_TYPE_VER" ON "AI_RESOURCE_VERSION"("NAMESPACE_ID", "NAME", "TYPE", "VERSION");
CREATE INDEX "IDX_AI_RESOURCE_VER_NAME" ON "AI_RESOURCE_VERSION"("NAME");
CREATE INDEX "IDX_AI_RESOURCE_VER_STATUS" ON "AI_RESOURCE_VERSION"("STATUS");
CREATE INDEX "IDX_AI_RESOURCE_VER_GMT_MODIFIED" ON "AI_RESOURCE_VERSION"("GMT_MODIFIED");

