/*
 * Copyright 1999-2023 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 -- ----------------------------
 -- sequence for tables
 -- ----------------------------
CREATE SEQUENCE "GROUP_CAPACITY_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "CONFIG_INFO_AGGR_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "CONFIG_INFO_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "CONFIG_INFO_BETA_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "CONFIG_INFO_TAG_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "CONFIG_TAGS_RELATION_NID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "TENANT_CAPACITY_ID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "HIS_CONFIG_INFO_NID_SEQ" INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE "TENANT_INFO_ID_SEQ" INCREMENT BY 1 START WITH 1;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
CREATE TABLE "CONFIG_TAGS_RELATION" (
	"ID" BIGINT NOT NULL,
	"TAG_NAME" VARCHAR(128 CHAR) NOT NULL,
	"TAG_TYPE" VARCHAR(64 CHAR) DEFAULT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) NOT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	"NID" BIGINT DEFAULT "CONFIG_TAGS_RELATION_NID_SEQ".NEXTVAL  NOT NULL,
	PRIMARY KEY ("NID")
);
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TAG_NAME" IS 'tag_name';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TAG_TYPE" IS 'tag_type';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."TENANT_ID" IS 'tenant_id';
COMMENT ON COLUMN "CONFIG_TAGS_RELATION"."NID" IS 'nid, 自增长标识';
COMMENT ON TABLE "CONFIG_TAGS_RELATION" IS 'config_tag_relation';

-- ----------------------------
-- Table structure for CONFIG_INFO_TAG
-- ----------------------------
CREATE TABLE "CONFIG_INFO_TAG" (
	"ID" BIGINT DEFAULT "CONFIG_INFO_TAG_ID_SEQ".NEXTVAL  NOT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) NOT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	"TAG_ID" VARCHAR(128 CHAR) NOT NULL,
	"APP_NAME" VARCHAR(128 CHAR) DEFAULT NULL,
	"CONTENT" CLOB NOT NULL,
	"MD5" VARCHAR(32 CHAR) DEFAULT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"SRC_USER" CLOB,
	"SRC_IP" VARCHAR(50 CHAR) DEFAULT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "CONFIG_INFO_TAG"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."TENANT_ID" IS 'tenant_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."TAG_ID" IS 'tag_id';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."CONTENT" IS 'content';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."MD5" IS 'md5';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "CONFIG_INFO_TAG"."SRC_IP" IS 'source ip';
COMMENT ON TABLE "CONFIG_INFO_TAG" IS 'config_info_tag';

-- ----------------------------
-- Table structure for CONFIG_INFO_BETA
-- ----------------------------
CREATE TABLE "CONFIG_INFO_BETA" (
	"ID" BIGINT DEFAULT "CONFIG_INFO_BETA_ID_SEQ".NEXTVAL  NOT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) NOT NULL,
	"APP_NAME" VARCHAR(128 CHAR) DEFAULT NULL,
	"CONTENT" CLOB NOT NULL,
	"BETA_IPS" VARCHAR(1024 CHAR) DEFAULT NULL,
	"MD5" VARCHAR(32 CHAR) DEFAULT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"SRC_USER" CLOB,
	"SRC_IP" VARCHAR(50 CHAR) DEFAULT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	"ENCRYPTED_DATA_KEY" VARCHAR(1024 CHAR) DEFAULT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "CONFIG_INFO_BETA"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."CONTENT" IS 'content';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."BETA_IPS" IS 'betaIps';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."MD5" IS 'md5';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."SRC_IP" IS 'source ip';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "CONFIG_INFO_BETA"."ENCRYPTED_DATA_KEY" IS '密钥';
COMMENT ON TABLE "CONFIG_INFO_BETA" IS 'config_info_beta';


-- ----------------------------
-- Table structure for CONFIG_INFO_AGGR
-- ----------------------------
CREATE TABLE "CONFIG_INFO_AGGR" (
	"ID" BIGINT DEFAULT "CONFIG_INFO_AGGR_ID_SEQ".NEXTVAL  NOT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) NOT NULL,
	"DATUM_ID" VARCHAR(255 CHAR) NOT NULL,
	"CONTENT" CLOB NOT NULL,
	"GMT_MODIFIED" TIMESTAMP NOT NULL,
	"APP_NAME" VARCHAR(128 CHAR) DEFAULT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."DATUM_ID" IS 'datum_id';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."CONTENT" IS '内容';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "CONFIG_INFO_AGGR"."TENANT_ID" IS '租户字段';
COMMENT ON TABLE "CONFIG_INFO_AGGR" IS '增加租户字段';

-- ----------------------------
-- Table structure for CONFIG_INFO
-- ----------------------------
CREATE TABLE "CONFIG_INFO" (
	"ID" BIGINT DEFAULT "CONFIG_INFO_ID_SEQ".NEXTVAL  NOT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) DEFAULT NULL,
	"CONTENT" CLOB NOT NULL,
	"MD5" VARCHAR(32 CHAR) DEFAULT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"SRC_USER" CLOB,
	"SRC_IP" VARCHAR(50 CHAR) DEFAULT NULL,
	"APP_NAME" VARCHAR(128 CHAR) DEFAULT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT 'PUBLIC',
	"C_DESC" VARCHAR(256 CHAR) DEFAULT NULL,
	"C_USE" VARCHAR(64 CHAR) DEFAULT NULL,
	"EFFECT" VARCHAR(64 CHAR) DEFAULT NULL,
	"TYPE" VARCHAR(64 CHAR) DEFAULT NULL,
	"C_SCHEMA" CLOB,
	"ENCRYPTED_DATA_KEY" VARCHAR(1024 CHAR) DEFAULT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "CONFIG_INFO"."ID" IS 'id';
COMMENT ON COLUMN "CONFIG_INFO"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "CONFIG_INFO"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "CONFIG_INFO"."CONTENT" IS 'content';
COMMENT ON COLUMN "CONFIG_INFO"."MD5" IS 'md5';
COMMENT ON COLUMN "CONFIG_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "CONFIG_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "CONFIG_INFO"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "CONFIG_INFO"."SRC_IP" IS 'source ip';
COMMENT ON COLUMN "CONFIG_INFO"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "CONFIG_INFO"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "CONFIG_INFO"."C_DESC" IS 'configuration description';
COMMENT ON COLUMN "CONFIG_INFO"."C_USE" IS 'configuration usage';
COMMENT ON COLUMN "CONFIG_INFO"."EFFECT" IS '配置生效的描述';
COMMENT ON COLUMN "CONFIG_INFO"."TYPE" IS '配置的类型';
COMMENT ON COLUMN "CONFIG_INFO"."C_SCHEMA" IS '配置的模式';
COMMENT ON COLUMN "CONFIG_INFO"."ENCRYPTED_DATA_KEY" IS '密钥';
COMMENT ON TABLE "CONFIG_INFO" IS 'config_info';

-- ----------------------------
-- Table structure for PERMISSIONS
-- ----------------------------
CREATE TABLE "PERMISSIONS" (
	"ROLE" VARCHAR(50 CHAR) NOT NULL,
	"RESOURCE" VARCHAR(128 CHAR) NOT NULL,
	"ACTION" VARCHAR(8 CHAR) NOT NULL
);
COMMENT ON COLUMN "PERMISSIONS"."ROLE" IS 'role';
COMMENT ON COLUMN "PERMISSIONS"."RESOURCE" IS 'resource';
COMMENT ON COLUMN "PERMISSIONS"."ACTION" IS 'action';

-- ----------------------------
-- Table structure for ROLES
-- ----------------------------
CREATE TABLE "ROLES" (
	"USERNAME" VARCHAR(50 CHAR) NOT NULL,
	"ROLE" VARCHAR(50 CHAR) NOT NULL
);
COMMENT ON COLUMN "ROLES"."USERNAME" IS 'username';
COMMENT ON COLUMN "ROLES"."ROLE" IS 'role';

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
CREATE TABLE "USERS" (
	"USERNAME" VARCHAR(50 CHAR) NOT NULL PRIMARY KEY,
	"PASSWORD" VARCHAR(500 CHAR) NOT NULL,
	"ENABLED" BOOLEAN NOT NULL
);
COMMENT ON COLUMN "USERS"."USERNAME" IS 'username';
COMMENT ON COLUMN "USERS"."PASSWORD" IS 'password';
COMMENT ON COLUMN "USERS"."ENABLED" IS 'enabled';

-- ----------------------------
-- Table structure for TENANT_INFO
-- ----------------------------
CREATE TABLE "TENANT_INFO" (
	"ID" BIGINT DEFAULT "TENANT_INFO_ID_SEQ".NEXTVAL  NOT NULL,
	"KP" VARCHAR(128 CHAR) NOT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	"TENANT_NAME" VARCHAR(128 CHAR) DEFAULT '',
	"TENANT_DESC" VARCHAR(256 CHAR) DEFAULT NULL,
	"CREATE_SOURCE" VARCHAR(32 CHAR) DEFAULT NULL,
	"GMT_CREATE" BIGINT NOT NULL,
	"GMT_MODIFIED" BIGINT NOT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "TENANT_INFO"."ID" IS 'id';
COMMENT ON COLUMN "TENANT_INFO"."KP" IS 'kp';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_ID" IS 'tenant_id';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_NAME" IS 'tenant_name';
COMMENT ON COLUMN "TENANT_INFO"."TENANT_DESC" IS 'tenant_desc';
COMMENT ON COLUMN "TENANT_INFO"."CREATE_SOURCE" IS 'create_source';
COMMENT ON COLUMN "TENANT_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "TENANT_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "TENANT_INFO" IS 'tenant_info';

-- ----------------------------
-- Table structure for TENANT_CAPACITY
-- ----------------------------
CREATE TABLE "TENANT_CAPACITY" (
	"ID" NUMBER DEFAULT "TENANT_CAPACITY_ID_SEQ".NEXTVAL  NOT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '' NOT NULL,
	"QUOTA" BIGINT DEFAULT '0' NOT NULL,
	"USAGE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_SIZE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_AGGR_COUNT" BIGINT DEFAULT '0' NOT NULL,
	"MAX_AGGR_SIZE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_HISTORY_COUNT" BIGINT DEFAULT '0' NOT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "TENANT_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "TENANT_CAPACITY"."TENANT_ID" IS 'Tenant ID';
COMMENT ON COLUMN "TENANT_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "TENANT_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "TENANT_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "TENANT_CAPACITY"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "TENANT_CAPACITY" IS '租户容量信息表';

-- ----------------------------
-- Table structure for HIS_CONFIG_INFO
-- ----------------------------
CREATE TABLE "HIS_CONFIG_INFO" (
	"ID" NUMBER NOT NULL,
	"NID" NUMBER DEFAULT "HIS_CONFIG_INFO_NID_SEQ".NEXTVAL  NOT NULL,
	"DATA_ID" VARCHAR(255 CHAR) NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) NOT NULL,
	"APP_NAME" VARCHAR(128 CHAR) DEFAULT NULL,
	"CONTENT" CLOB NOT NULL,
	"MD5" VARCHAR(32 CHAR) DEFAULT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"SRC_USER" CLOB,
	"SRC_IP" VARCHAR(50 CHAR) DEFAULT NULL,
	"OP_TYPE" CHAR(10 CHAR) DEFAULT NULL,
	"TENANT_ID" VARCHAR(128 CHAR) DEFAULT '',
	"ENCRYPTED_DATA_KEY" VARCHAR(1024 CHAR) DEFAULT NULL,
	PRIMARY KEY ("NID")
);
COMMENT ON COLUMN "HIS_CONFIG_INFO"."ID" IS 'id';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."NID" IS 'nid, 自增标识';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."DATA_ID" IS 'data_id';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."GROUP_ID" IS 'group_id';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."APP_NAME" IS 'app_name';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."CONTENT" IS 'content';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."MD5" IS 'md5';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."SRC_USER" IS 'source user';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."SRC_IP" IS 'source ip';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."OP_TYPE" IS 'operation type';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."TENANT_ID" IS '租户字段';
COMMENT ON COLUMN "HIS_CONFIG_INFO"."ENCRYPTED_DATA_KEY" IS '密钥';
COMMENT ON TABLE "HIS_CONFIG_INFO" IS '多租户改造';

-- ----------------------------
-- Table structure for GROUP_CAPACITY
-- ----------------------------
CREATE TABLE "GROUP_CAPACITY" (
	"ID" NUMBER DEFAULT "GROUP_CAPACITY_ID_SEQ".NEXTVAL  NOT NULL,
	"GROUP_ID" VARCHAR(128 CHAR) DEFAULT '' NOT NULL,
	"QUOTA" BIGINT DEFAULT '0' NOT NULL,
	"USAGE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_SIZE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_AGGR_COUNT" BIGINT DEFAULT '0' NOT NULL,
	"MAX_AGGR_SIZE" BIGINT DEFAULT '0' NOT NULL,
	"MAX_HISTORY_COUNT" BIGINT DEFAULT '0' NOT NULL,
	"GMT_CREATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"GMT_MODIFIED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "GROUP_CAPACITY"."ID" IS '主键ID';
COMMENT ON COLUMN "GROUP_CAPACITY"."GROUP_ID" IS 'Group ID，空字符表示整个集群';
COMMENT ON COLUMN "GROUP_CAPACITY"."QUOTA" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."USAGE" IS '使用量';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_SIZE" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_AGGR_COUNT" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_AGGR_SIZE" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "GROUP_CAPACITY"."MAX_HISTORY_COUNT" IS '最大变更历史数量';
COMMENT ON COLUMN "GROUP_CAPACITY"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "GROUP_CAPACITY"."GMT_MODIFIED" IS '修改时间';
COMMENT ON TABLE "GROUP_CAPACITY" IS '集群、各Group容量信息表';


-- ----------------------------
-- Table index for tables
-- ----------------------------

CREATE UNIQUE INDEX "UK_CONFIGINFO_DATAGROUPTENANT" ON "CONFIG_INFO"("DATA_ID", "GROUP_ID", "TENANT_ID");

CREATE UNIQUE INDEX "UK_CONFIGINFOAGGR_DATAGROUPTENANTDATUM" ON "CONFIG_INFO_AGGR"("DATA_ID", "GROUP_ID", "TENANT_ID", "DATUM_ID");

CREATE UNIQUE INDEX "UK_CONFIGINFOBETA_DATAGROUPTENANT" ON "CONFIG_INFO_BETA"("DATA_ID", "GROUP_ID", "TENANT_ID");

CREATE UNIQUE INDEX "UK_CONFIGINFOTAG_DATAGROUPTENANTTAG" ON "CONFIG_INFO_TAG"("DATA_ID", "GROUP_ID", "TENANT_ID", "TAG_ID");

CREATE UNIQUE INDEX "UK_CONFIGTAGRELATION_CONFIGIDTAG" ON "CONFIG_TAGS_RELATION"("ID", "TAG_NAME", "TAG_TYPE");

CREATE INDEX "IDX_TENANT_ID" ON "CONFIG_TAGS_RELATION"("TENANT_ID");

CREATE INDEX "IDX_DID" ON "HIS_CONFIG_INFO"("DATA_ID");

CREATE INDEX "IDX_GMT_MODIFIED" ON "HIS_CONFIG_INFO"("GMT_MODIFIED");

CREATE INDEX "IDX_GMT_CREATE" ON "HIS_CONFIG_INFO"("GMT_CREATE");

CREATE UNIQUE INDEX "UK_GROUP_ID" ON "GROUP_CAPACITY"("GROUP_ID");

CREATE UNIQUE INDEX "UK_TENANT_ID" ON "TENANT_CAPACITY"("TENANT_ID");

CREATE UNIQUE INDEX "UK_TENANT_INFO_KPTENANTID" ON "TENANT_INFO"("KP", "TENANT_ID");

CREATE UNIQUE INDEX "IDX_USER_ROLE" ON "ROLES"("USERNAME" ASC, "ROLE" ASC);

CREATE UNIQUE INDEX "UK_ROLE_PERMISSION" ON "PERMISSIONS"("ROLE", "RESOURCE", "ACTION");

