<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.alibaba.nacos</groupId>
        <artifactId>nacos-datasource-plugin-ext</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>nacos-xuguDB-datasource-plugin-ext</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <xugu-jdbc.version>12.3.5</xugu-jdbc.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>com.xugudb</groupId>
            <artifactId>xugu-jdbc</artifactId>
            <version>${xugu-jdbc.version}</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-datasource-plugin-ext-base</artifactId>
            <version>${revision}</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

    </dependencies>
</project>